package com.ashoo.ingestion;

import com.ashoo.storage.entity.EnvironmentalSnapshot;
import com.ashoo.storage.entity.SymptomLog;
import com.ashoo.storage.repository.EnvironmentalSnapshotRepository;
import com.ashoo.storage.repository.SymptomLogRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * Generates synthetic demo data for the three Ashoo personas.
 *
 * The environmental data is REAL (fetched from Open-Meteo for Amsterdam);
 * the symptom logs are SYNTHETIC — generated by applying each persona's
 * trigger rules to the real environmental readings. This creates realistic
 * correlation patterns for the demo without fabricating environmental data.
 *
 * All synthetic rows are marked {@code data_origin = 'SEEDED_SYNTHETIC'}.
 */
@Service
public class SeedDemoService {

    private static final Logger log = LoggerFactory.getLogger(SeedDemoService.class);

    /** Amsterdam coordinates — required for Open-Meteo pollen data (CAMS is Europe-only). */
    private static final double AMSTERDAM_LAT = 52.3676;
    private static final double AMSTERDAM_LON = 4.9041;
    private static final String AMSTERDAM_CITY = "Amsterdam, Netherlands";

    private static final Map<String, String> PERSONA_DESCRIPTIONS = Map.of(
            "alex",   "Low sensitivity — symptoms only under strict multi-trigger conditions",
            "jordan", "Moderate sensitivity — clear seasonal patterns",
            "morgan", "High sensitivity — frequent episodes, non-obvious triggers"
    );

    private final IngestionService ingestionService;
    private final EnvironmentalSnapshotRepository snapshotRepo;
    private final SymptomLogRepository symptomRepo;

    public SeedDemoService(IngestionService ingestionService,
                            EnvironmentalSnapshotRepository snapshotRepo,
                            SymptomLogRepository symptomRepo) {
        this.ingestionService = ingestionService;
        this.snapshotRepo = snapshotRepo;
        this.symptomRepo = symptomRepo;
    }

    /**
     * Seeds all three demo personas with 90 days of real environmental data
     * and synthetic symptom logs tuned to each persona's sensitivity profile.
     *
     * The real data is fetched once from Open-Meteo and reused across personas —
     * they all "live" in Amsterdam for pollen availability. Their symptom
     * responses to those same conditions differ by persona.
     *
     * @return map of persona name to row counts inserted
     */
    public Map<String, Integer> seedAllPersonas() {
        log.info("Seeding demo data for all three personas (Amsterdam, 90 days)");

        // Fetch 90 days of real environmental history once
        int envRows = ingestionService.seedHistory(AMSTERDAM_LAT, AMSTERDAM_LON, AMSTERDAM_CITY, 90);
        log.info("Seeded {} real environmental rows for Amsterdam", envRows);

        // Fetch the snapshots back to use as input for symptom generation
        LocalDate endDate = LocalDate.now().minusDays(1);
        LocalDate startDate = endDate.minusDays(90);
        List<EnvironmentalSnapshot> snapshots = snapshotRepo.findByDateRange(
                "ashoo-user",
                startDate.atStartOfDay(ZoneOffset.UTC).toInstant(),
                endDate.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant());

        Map<String, Integer> results = Map.of(
                "alex",   seedPersona("alex",   snapshots),
                "jordan", seedPersona("jordan", snapshots),
                "morgan", seedPersona("morgan", snapshots)
        );

        log.info("Demo seeding complete: {}", results);
        return results;
    }

    /**
     * Seeds one persona with synthetic symptom logs derived from the real environmental data.
     *
     * Each persona has a different trigger rule applied to the same environmental history,
     * producing different symptom patterns. The rules reflect the CLAUDE.md persona specs.
     *
     * @param persona   "alex", "jordan", or "morgan"
     * @param snapshots the real environmental snapshots to correlate against
     * @return number of symptom log rows inserted
     */
    public int seedPersona(String persona, List<EnvironmentalSnapshot> snapshots) {
        String userId = "demo-" + persona;
        Random rng = new Random(persona.hashCode());

        List<SymptomLog> logs = new ArrayList<>();

        // Group snapshots by day and pick the max reading for that day
        Map<LocalDate, EnvironmentalSnapshot> byDay = new java.util.LinkedHashMap<>();
        for (EnvironmentalSnapshot s : snapshots) {
            LocalDate day = s.getRecordedAt().atZone(ZoneOffset.UTC).toLocalDate();
            byDay.merge(day, s, (a, b) ->
                    (a.getPm25() != null && b.getPm25() != null && a.getPm25() >= b.getPm25()) ? a : b);
        }

        for (Map.Entry<LocalDate, EnvironmentalSnapshot> entry : byDay.entrySet()) {
            LocalDate day = entry.getKey();
            EnvironmentalSnapshot env = entry.getValue();
            int severity = computeSeverity(persona, env, rng);

            if (severity > 0) {
                SymptomLog sl = new SymptomLog();
                sl.setUserId(userId);
                sl.setLoggedAt(day.atTime(8, 0).toInstant(ZoneOffset.UTC));
                sl.setSeverity(severity);
                sl.setCityName(AMSTERDAM_CITY);
                sl.setNotes(buildNote(persona, severity));
                sl.setDataOrigin("SEEDED_SYNTHETIC");
                logs.add(sl);
            }
        }

        if (!logs.isEmpty()) {
            symptomRepo.saveAll(logs);
        }

        log.info("Seeded {} symptom days for persona '{}'", logs.size(), persona);
        return logs.size();
    }

    /**
     * Computes a synthetic severity score (0–10) for a given persona and environmental reading.
     *
     * Rules from CLAUDE.md:
     * - Alex (low):    pm25 > 25 AND humidity > 70% simultaneously. Severity capped at 4.
     * - Jordan (mod):  pm25 > 18 OR pollen_grass > 30. Severity 3–7. Seasonal pattern.
     * - Morgan (high): pm25 > 12 OR pollen > 15 OR humidity > 60%. Severity 7–10 often.
     *
     * Small random noise is added so consecutive days are not identical.
     *
     * @param persona the persona name
     * @param env     the environmental snapshot for this day
     * @param rng     seeded random for reproducibility across calls
     * @return severity 0–10 (0 = no symptoms)
     */
    int computeSeverity(String persona, EnvironmentalSnapshot env, Random rng) {
        double pm25      = env.getPm25()      != null ? env.getPm25()      : 0;
        double humidity  = env.getHumidityPct() != null ? env.getHumidityPct() : 0;
        double grass     = env.getPollenGrass() != null ? env.getPollenGrass() : 0;
        double pollen    = Math.max(grass, env.getPollenBirch() != null ? env.getPollenBirch() : 0);

        return switch (persona) {
            case "alex" -> {
                // Strict AND — both conditions must be met
                if (pm25 > 25 && humidity > 70) {
                    yield Math.min(4, 1 + rng.nextInt(4));
                }
                yield 0;
            }
            case "jordan" -> {
                // OR condition with seasonal pollen weight
                boolean triggered = pm25 > 18 || grass > 30;
                if (!triggered) yield 0;
                yield 3 + rng.nextInt(5); // 3–7
            }
            case "morgan" -> {
                // Very sensitive — multiple low-level triggers
                boolean triggered = pm25 > 12 || pollen > 15 || humidity > 60;
                if (!triggered) yield 0;
                // Frequently severe
                int base = 5 + rng.nextInt(5); // 5–9
                // Occasionally extreme
                yield rng.nextInt(10) == 0 ? 10 : base;
            }
            default -> 0;
        };
    }

    private String buildNote(String persona, int severity) {
        return switch (persona) {
            case "alex"   -> severity >= 3 ? "Noticeable tightness today" : "Mild scratchy throat";
            case "jordan" -> severity >= 6 ? "Bad allergy day — sneezing nonstop" : "Eyes itchy, runny nose";
            case "morgan" -> severity >= 8 ? "Severe episode — had to use rescue inhaler"
                                           : "Significant symptoms, hard to be outside";
            default -> "Symptoms noted";
        };
    }
}
