package com.ashoo.ingestion;

import com.ashoo.storage.entity.EnvironmentalSnapshot;
import com.ashoo.storage.entity.SymptomLog;
import com.ashoo.storage.repository.BriefingLogRepository;
import com.ashoo.storage.repository.EnvironmentalSnapshotRepository;
import com.ashoo.storage.repository.SymptomLogRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * Generates synthetic demo data for the three Ashoo personas.
 *
 * The environmental data is REAL (fetched from Open-Meteo for Amsterdam);
 * the symptom logs are SYNTHETIC — generated by applying each persona's
 * trigger rules to the real environmental readings. This creates realistic
 * correlation patterns for the demo without fabricating environmental data.
 *
 * All synthetic rows are marked {@code data_origin = 'SEEDED_SYNTHETIC'}.
 */
@Service
public class SeedDemoService {

    private static final Logger log = LoggerFactory.getLogger(SeedDemoService.class);

    /** Amsterdam coordinates — required for Open-Meteo pollen data (CAMS is Europe-only). */
    private static final double AMSTERDAM_LAT = 52.3676;
    private static final double AMSTERDAM_LON = 4.9041;
    private static final String AMSTERDAM_CITY = "Amsterdam, Netherlands";

    /**
     * The single default user the whole V1 app reads from (dashboard, risk, briefing).
     * Demo seeding also populates THIS user so that, after seeding, the live dashboard
     * and Insights light up immediately — otherwise the persona data lives under
     * separate {@code demo-*} ids the read endpoints never touch.
     */
    private static final String DEFAULT_USER = "ashoo-user";

    /** Which persona's trigger profile to project onto the default user. "morgan" is the
     *  high-sensitivity profile, which yields the richest correlations and mismatch days. */
    private static final String DEFAULT_USER_PROFILE = "morgan";

    private static final Map<String, String> PERSONA_DESCRIPTIONS = Map.of(
            "alex",   "Low sensitivity — symptoms only under strict multi-trigger conditions",
            "jordan", "Moderate sensitivity — clear seasonal patterns",
            "morgan", "High sensitivity — frequent episodes, non-obvious triggers"
    );

    private final IngestionService ingestionService;
    private final EnvironmentalSnapshotRepository snapshotRepo;
    private final SymptomLogRepository symptomRepo;
    private final BriefingLogRepository briefingLogRepo;

    public SeedDemoService(IngestionService ingestionService,
                            EnvironmentalSnapshotRepository snapshotRepo,
                            SymptomLogRepository symptomRepo,
                            BriefingLogRepository briefingLogRepo) {
        this.ingestionService = ingestionService;
        this.snapshotRepo = snapshotRepo;
        this.symptomRepo = symptomRepo;
        this.briefingLogRepo = briefingLogRepo;
    }

    /**
     * Seeds all three demo personas with 90 days of real environmental data
     * and synthetic symptom logs tuned to each persona's sensitivity profile.
     *
     * The real data is fetched once from Open-Meteo and reused across personas —
     * they all "live" in Amsterdam for pollen availability. Their symptom
     * responses to those same conditions differ by persona.
     *
     * @return map of persona name to row counts inserted
     */
    public Map<String, Integer> seedAllPersonas() {
        log.info("Seeding demo data for all three personas (Amsterdam, 90 days)");

        // Fetch 90 days of real environmental history once
        int envRows = ingestionService.seedHistory(AMSTERDAM_LAT, AMSTERDAM_LON, AMSTERDAM_CITY, 90);
        log.info("Seeded {} real environmental rows for Amsterdam", envRows);

        // Fetch the snapshots back to use as input for symptom generation
        LocalDate endDate = LocalDate.now().minusDays(1);
        LocalDate startDate = endDate.minusDays(90);
        List<EnvironmentalSnapshot> snapshots = snapshotRepo.findByDateRange(
                "ashoo-user",
                startDate.atStartOfDay(ZoneOffset.UTC).toInstant(),
                endDate.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant());

        // Seed the three browseable personas under their own ids...
        Map<String, Integer> results = new java.util.LinkedHashMap<>();
        results.put("alex",   seedFor("demo-alex",   "alex",   snapshots));
        results.put("jordan", seedFor("demo-jordan", "jordan", snapshots));
        results.put("morgan", seedFor("demo-morgan", "morgan", snapshots));

        // ...and ALSO project one profile onto the default user so the live dashboard,
        // risk score, briefing, and Insights have data the moment seeding finishes.
        results.put(DEFAULT_USER, seedFor(DEFAULT_USER, DEFAULT_USER_PROFILE, snapshots));

        // Drop any same-day cached briefings (default user + personas) so each regenerates
        // against the freshly seeded numbers instead of serving a stale pre-seed briefing.
        briefingLogRepo.deleteByUserId(DEFAULT_USER);
        briefingLogRepo.deleteByUserId("demo-alex");
        briefingLogRepo.deleteByUserId("demo-jordan");
        briefingLogRepo.deleteByUserId("demo-morgan");

        log.info("Demo seeding complete: {}", results);
        return results;
    }

    /**
     * Backwards-compatible entry point that seeds a persona under its conventional
     * {@code demo-<persona>} id. Retained so existing callers/tests keep working.
     *
     * @param persona   "alex", "jordan", or "morgan"
     * @param snapshots the real environmental snapshots to correlate against
     * @return number of symptom log rows inserted
     */
    public int seedPersona(String persona, List<EnvironmentalSnapshot> snapshots) {
        return seedFor("demo-" + persona, persona, snapshots);
    }

    /**
     * Seeds synthetic symptom logs for a given user id using a chosen persona's trigger rules.
     *
     * Separating the user id from the persona lets us reuse one trigger profile for both a
     * browseable {@code demo-*} persona AND the default user — the only difference is which
     * id the rows are written under. The rules reflect the CLAUDE.md persona specs.
     *
     * @param userId    the user id to write logs under (e.g. "demo-morgan" or "ashoo-user")
     * @param persona   which trigger profile to apply: "alex", "jordan", or "morgan"
     * @param snapshots the real environmental snapshots to correlate against
     * @return number of symptom log rows inserted
     */
    public int seedFor(String userId, String persona, List<EnvironmentalSnapshot> snapshots) {
        Random rng = new Random((userId + persona).hashCode());

        // Clear any prior synthetic logs for this user so re-seeding is idempotent
        // (never touches REAL user entries).
        symptomRepo.deleteSyntheticByUserId(userId);

        // Seeded symptom logs MUST carry the same city as the shared environmental
        // data (Amsterdam). The correlation engine filters symptom days to the tracked
        // location, so a divergent city (e.g. a persona's cosmetic display location)
        // would discard every symptom day and learn a zero-weight model. The persona's
        // human-facing location lives in the frontend and /demo/profiles, not here.
        String cityName = AMSTERDAM_CITY;

        List<SymptomLog> logs = new ArrayList<>();

        // Group snapshots by day and pick the max reading for that day
        Map<LocalDate, EnvironmentalSnapshot> byDay = new java.util.LinkedHashMap<>();
        for (EnvironmentalSnapshot s : snapshots) {
            LocalDate day = s.getRecordedAt().atZone(ZoneOffset.UTC).toLocalDate();
            byDay.merge(day, s, (a, b) ->
                    (a.getPm25() != null && b.getPm25() != null && a.getPm25() >= b.getPm25()) ? a : b);
        }

        for (Map.Entry<LocalDate, EnvironmentalSnapshot> entry : byDay.entrySet()) {
            LocalDate day = entry.getKey();
            EnvironmentalSnapshot env = entry.getValue();
            int severity = computeSeverity(persona, env, rng);

            if (severity > 0) {
                SymptomLog sl = new SymptomLog();
                sl.setUserId(userId);
                sl.setLoggedAt(day.atTime(8, 0).toInstant(ZoneOffset.UTC));
                sl.setSeverity(severity);
                sl.setCityName(cityName);
                sl.setNotes(buildNote(persona, severity));
                sl.setDataOrigin("SEEDED_SYNTHETIC");
                logs.add(sl);
            }
        }

        if (!logs.isEmpty()) {
            symptomRepo.saveAll(logs);
        }

        log.info("Seeded {} symptom days for persona '{}'", logs.size(), persona);
        return logs.size();
    }

    /**
     * Computes a synthetic severity score (0-10) for a given persona and environmental reading.
     *
     * The three personas are deliberately driven by DIFFERENT factors at DIFFERENT
     * frequencies, so their learned fingerprints, symptom counts, confidence levels, and
     * trend shapes look clearly distinct rather than blurring together:
     *
     * - Alex (low sensitivity): only genuinely poor air bothers him, and only mildly.
     *   Single driver = PM2.5. Rare days, severity 1-3 (stays LOW confidence).
     * - Jordan (moderate): a classic pollen sufferer with a seasonal pattern. Single
     *   driver = grass/birch pollen. Regular days in season, severity 3-6.
     * - Morgan (high sensitivity): reacts to many things at low levels, often badly.
     *   Multi-driver = PM2.5 OR pollen OR humidity OR a pressure drop. Frequent, severe 6-10.
     *
     * Small random noise keeps consecutive days from being identical.
     *
     * @param persona the persona name
     * @param env     the environmental snapshot for this day
     * @param rng     seeded random for reproducibility across calls
     * @return severity 0-10 (0 = no symptoms)
     */
    int computeSeverity(String persona, EnvironmentalSnapshot env, Random rng) {
        double pm25     = env.getPm25() != null ? env.getPm25() : 0;
        double humidity = env.getHumidityPct() != null ? env.getHumidityPct() : 0;
        double grass    = env.getPollenGrass() != null ? env.getPollenGrass() : 0;
        double birch    = env.getPollenBirch() != null ? env.getPollenBirch() : 0;
        double pollen   = Math.max(grass, birch);
        double pressureDrop = env.getPressureDrop3h() != null ? env.getPressureDrop3h() : 0;

        return switch (persona) {
            case "alex" -> {
                // Pollution only, and only when it's genuinely poor. Rare and mild,
                // so he stays at LOW confidence (the "keep logging" story).
                if (pm25 > 26) yield 1 + rng.nextInt(3); // 1-3
                yield 0;
            }
            case "jordan" -> {
                // Pollen driven, seasonal. Regular moderate days when pollen is up.
                if (pollen > 12) yield 3 + rng.nextInt(4); // 3-6
                yield 0;
            }
            case "morgan" -> {
                // Sensitive across several factors, but NOT every single day, so the
                // engine still has good days to contrast against and learns clear,
                // low personal thresholds (which is what makes his risk read high).
                boolean triggered = pm25 > 11 || pollen > 8 || pressureDrop > 3;
                if (!triggered) yield 0;
                int base = 6 + rng.nextInt(4); // 6-9
                yield rng.nextInt(8) == 0 ? 10 : base; // occasional 10
            }
            default -> 0;
        };
    }

    private String buildNote(String persona, int severity) {
        return switch (persona) {
            case "alex"   -> severity >= 3 ? "Noticeable tightness on a hazy day" : "Mild scratchy throat";
            case "jordan" -> severity >= 6 ? "Rough pollen day, sneezing nonstop" : "Itchy eyes, runny nose";
            case "morgan" -> severity >= 8 ? "Severe episode, needed my rescue inhaler"
                                           : "Significant symptoms, hard to be outside";
            default -> "Symptoms noted";
        };
    }
}
