package com.ashoo.ingestion;

import com.ashoo.storage.entity.ConsentRecord;
import com.ashoo.storage.entity.EnvironmentalSnapshot;
import com.ashoo.storage.entity.ReminderRule;
import com.ashoo.storage.entity.SymptomLog;
import com.ashoo.storage.repository.BriefingLogRepository;
import com.ashoo.storage.repository.ConsentRecordRepository;
import com.ashoo.storage.repository.EnvironmentalSnapshotRepository;
import com.ashoo.storage.repository.ReminderRuleRepository;
import com.ashoo.storage.repository.SymptomLogRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * Generates synthetic demo data for the three Ashoo personas.
 *
 * The environmental data is REAL (fetched from Open-Meteo for Amsterdam);
 * the symptom logs are SYNTHETIC — generated by applying each persona's
 * trigger rules to the real environmental readings. This creates realistic
 * correlation patterns for the demo without fabricating environmental data.
 *
 * All synthetic rows are marked {@code data_origin = 'SEEDED_SYNTHETIC'}.
 */
@Service
public class SeedDemoService {

    private static final Logger log = LoggerFactory.getLogger(SeedDemoService.class);

    /** Display name / fallback city for the {@link #seedPersona} convenience path. */
    private static final String AMSTERDAM_CITY = "Amsterdam, Netherlands";

    /**
     * The single default user the whole V1 app reads from (dashboard, risk, briefing).
     * Demo seeding also populates THIS user so that, after seeding, the live dashboard
     * and Insights light up immediately — otherwise the persona data lives under
     * separate {@code demo-*} ids the read endpoints never touch.
     */
    private static final String DEFAULT_USER = "ashoo-user";

    /**
     * One persona's home: the user id its rows are written under, the trigger profile
     * that shapes its synthetic symptoms, and the REAL city whose environmental history
     * is fetched for it. Each one lives in a distinct city, so its Personal Risk Index
     * reflects that city's actual conditions correlated with its own logs.
     */
    private record PersonaSeed(String userId, String profile,
                               double lat, double lon, String city) {}

    /**
     * "You" (the default user) plus the three browseable personas, each in its own city.
     * "You" uses Sharon, MA, the configured home location the live scheduler also ingests,
     * so the dashboard's conditions match where the user actually is (US air quality and
     * weather; Open-Meteo has no pollen outside Europe). The browseable personas use
     * European cities so their pollen-driven profiles stay meaningful.
     */
    private static final List<PersonaSeed> PERSONA_SEEDS = List.of(
            new PersonaSeed(DEFAULT_USER,  "morgan", 42.1237, -71.1847, "Sharon, MA"),
            new PersonaSeed("demo-alex",   "alex",   51.5072,  -0.1276, "London, United Kingdom"),
            new PersonaSeed("demo-jordan", "jordan", 52.5200,  13.4050, "Berlin, Germany"),
            new PersonaSeed("demo-morgan", "morgan", 48.8566,   2.3522, "Paris, France")
    );

    private static final Map<String, String> PERSONA_DESCRIPTIONS = Map.of(
            "alex",   "Low sensitivity: symptoms only under strict multi-trigger conditions",
            "jordan", "Moderate sensitivity: clear seasonal patterns",
            "morgan", "High sensitivity: frequent episodes, non-obvious triggers"
    );

    /** One pre-configured reminder for a persona: the score that trips it and the user's note. */
    private record ReminderSpec(double threshold, String note) {}

    /**
     * Pre-configured reminders per demo persona, tuned to each one's sensitivity. These are
     * the persona's OWN notes echoed back when their risk crosses the threshold — Ashoo never
     * invents advice. Seeded only for the synthetic personas; the real "you" user manages
     * their own reminders through the consent-gated UI.
     */
    private static final Map<String, List<ReminderSpec>> PERSONA_REMINDERS = Map.of(
            DEFAULT_USER, List.of(
                    new ReminderSpec(40, "Air's getting iffy, so carry my reliever inhaler just in case."),
                    new ReminderSpec(65, "Conditions are rough today, so limit time outdoors and follow my action plan.")),
            "demo-alex", List.of(
                    new ReminderSpec(35, "Hazy air today, so keep my reliever inhaler with me and take it easy outside.")),
            "demo-jordan", List.of(
                    new ReminderSpec(45, "Pollen's climbing, so take my antihistamine before heading out."),
                    new ReminderSpec(65, "High pollen day, so keep the windows shut and limit time outdoors.")),
            "demo-morgan", List.of(
                    new ReminderSpec(50, "Conditions are stacking up, so carry my rescue inhaler today."),
                    new ReminderSpec(72, "Rough air day, so plan to stay indoors and follow my action plan."))
    );

    private final IngestionService ingestionService;
    private final EnvironmentalSnapshotRepository snapshotRepo;
    private final SymptomLogRepository symptomRepo;
    private final BriefingLogRepository briefingLogRepo;
    private final ReminderRuleRepository reminderRuleRepo;
    private final ConsentRecordRepository consentRepo;

    public SeedDemoService(IngestionService ingestionService,
                            EnvironmentalSnapshotRepository snapshotRepo,
                            SymptomLogRepository symptomRepo,
                            BriefingLogRepository briefingLogRepo,
                            ReminderRuleRepository reminderRuleRepo,
                            ConsentRecordRepository consentRepo) {
        this.ingestionService = ingestionService;
        this.snapshotRepo = snapshotRepo;
        this.symptomRepo = symptomRepo;
        this.briefingLogRepo = briefingLogRepo;
        this.reminderRuleRepo = reminderRuleRepo;
        this.consentRepo = consentRepo;
    }

    /**
     * Seeds the default user and all three personas, each with 90 days of its OWN
     * city's real environmental history and synthetic symptom logs tuned to its
     * sensitivity profile.
     *
     * Each persona lives in a distinct European city, so its environment — and
     * therefore its Personal Risk Index — genuinely differs. The synthetic symptoms
     * are generated from that city's real readings, so the learned model reflects how
     * that individual would respond to their own local conditions.
     *
     * @return map of persona name (or "ashoo-user") to symptom row counts inserted
     */
    public Map<String, Integer> seedAllPersonas() {
        log.info("Seeding demo data: each persona in its own EU city with its own 90-day history");

        Map<String, Integer> results = new java.util.LinkedHashMap<>();
        for (PersonaSeed ps : PERSONA_SEEDS) {
            int envRows = ingestionService.seedHistory(ps.lat(), ps.lon(), ps.city(), 90, ps.userId());
            log.info("Seeded {} real environmental rows for {} ({})", envRows, ps.userId(), ps.city());

            // Read that persona's own freshly-stored history back as the input for
            // symptom generation and correlation.
            LocalDate endDate = LocalDate.now().minusDays(1);
            LocalDate startDate = endDate.minusDays(90);
            List<EnvironmentalSnapshot> snapshots = snapshotRepo.findByDateRange(
                    ps.userId(),
                    startDate.atStartOfDay(ZoneOffset.UTC).toInstant(),
                    endDate.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant());

            results.put(resultKey(ps.userId()),
                    seedFor(ps.userId(), ps.profile(), snapshots, ps.city()));
        }

        // Drop any same-day cached briefings (default user + personas) so each regenerates
        // against the freshly seeded numbers instead of serving a stale pre-seed briefing.
        briefingLogRepo.deleteByUserId(DEFAULT_USER);
        briefingLogRepo.deleteByUserId("demo-alex");
        briefingLogRepo.deleteByUserId("demo-jordan");
        briefingLogRepo.deleteByUserId("demo-morgan");

        // Give each persona its pre-configured reminders so the reminders surface is
        // populated when switching personas.
        seedRemindersAndConsent();

        log.info("Demo seeding complete: {}", results);
        return results;
    }

    /** Short result key: the persona name for {@code demo-*} ids, else the id itself. */
    private static String resultKey(String userId) {
        return userId.startsWith("demo-") ? userId.substring("demo-".length()) : userId;
    }

    /**
     * Installs each demo persona's pre-configured reminder rules (and a demo consent
     * record so the consent-gated engine will surface them). Idempotent: existing rules
     * for a persona are cleared first, and consent is only granted if absent.
     *
     * Only the synthetic personas are seeded — the real "you" user keeps the genuine
     * consent flow and sets up their own reminders.
     */
    private void seedRemindersAndConsent() {
        for (Map.Entry<String, List<ReminderSpec>> entry : PERSONA_REMINDERS.entrySet()) {
            String userId = entry.getKey();
            ensureDemoConsent(userId);

            List<ReminderRule> existing = reminderRuleRepo.findActiveByUserId(userId);
            if (!existing.isEmpty()) reminderRuleRepo.deleteAll(existing);

            for (ReminderSpec spec : entry.getValue()) {
                ReminderRule rule = new ReminderRule();
                rule.setUserId(userId);
                rule.setRiskScoreThreshold(spec.threshold());
                rule.setUserNote(spec.note());
                rule.setMedicationId(null);
                rule.setTimeWindowStart(null);
                rule.setTimeWindowEnd(null);
                rule.setIsActive(true);
                rule.setCreatedAt(Instant.now());
                reminderRuleRepo.save(rule);
            }
            log.info("Seeded {} reminder rule(s) for {}", entry.getValue().size(), userId);
        }
    }

    /** Grants a demo consent record for a synthetic persona if it has none yet. */
    private void ensureDemoConsent(String userId) {
        if (consentRepo.findLatestByUserId(userId).isPresent()) return;
        ConsentRecord consent = new ConsentRecord();
        consent.setUserId(userId);
        consent.setConsentedAt(Instant.now());
        consent.setDisclaimerText("Seeded demo persona: advisory only, not medical advice.");
        consentRepo.save(consent);
    }

    /**
     * Re-seeds just the default user ("You") with a new location. Clears old env
     * data and synthetic symptoms, fetches fresh history for the specified city,
     * and generates new symptom logs so the model can be recomputed against the
     * new location's actual conditions.
     *
     * @param lat  latitude of the new location
     * @param lon  longitude of the new location
     * @param city display name of the new location
     * @return number of symptom rows inserted
     */
    public int reseedDefaultUser(double lat, double lon, String city) {
        log.info("Re-seeding default user for new location: {} ({}, {})", city, lat, lon);

        snapshotRepo.deleteByUserId(DEFAULT_USER);

        int envRows = ingestionService.seedHistory(lat, lon, city, 90, DEFAULT_USER);
        log.info("Seeded {} env rows for {} under default user", envRows, city);

        LocalDate endDate = LocalDate.now().minusDays(1);
        LocalDate startDate = endDate.minusDays(90);
        List<EnvironmentalSnapshot> snapshots = snapshotRepo.findByDateRange(
                DEFAULT_USER,
                startDate.atStartOfDay(ZoneOffset.UTC).toInstant(),
                endDate.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant());

        int symptomRows = seedFor(DEFAULT_USER, "morgan", snapshots, city);
        briefingLogRepo.deleteByUserId(DEFAULT_USER);
        return symptomRows;
    }

    /**
     * Backwards-compatible entry point that seeds a persona under its conventional
     * {@code demo-<persona>} id. Retained so existing callers/tests keep working.
     *
     * @param persona   "alex", "jordan", or "morgan"
     * @param snapshots the real environmental snapshots to correlate against
     * @return number of symptom log rows inserted
     */
    public int seedPersona(String persona, List<EnvironmentalSnapshot> snapshots) {
        return seedFor("demo-" + persona, persona, snapshots, AMSTERDAM_CITY);
    }

    /**
     * Seeds synthetic symptom logs for a given user id using a chosen persona's trigger rules.
     *
     * Separating the user id from the persona lets us reuse one trigger profile for both a
     * browseable {@code demo-*} persona AND the default user — the only difference is which
     * id the rows are written under. The rules reflect the CLAUDE.md persona specs.
     *
     * @param userId    the user id to write logs under (e.g. "demo-morgan" or "ashoo-user")
     * @param persona   which trigger profile to apply: "alex", "jordan", or "morgan"
     * @param snapshots the real environmental snapshots to correlate against
     * @param cityName  the city to stamp on each log — MUST match the city of {@code snapshots}
     *                  so the correlation engine's location filter keeps these symptom days
     * @return number of symptom log rows inserted
     */
    public int seedFor(String userId, String persona, List<EnvironmentalSnapshot> snapshots,
                       String cityName) {
        Random rng = new Random((userId + persona).hashCode());

        // Clear any prior synthetic logs for this user so re-seeding is idempotent
        // (never touches REAL user entries).
        symptomRepo.deleteSyntheticByUserId(userId);

        List<SymptomLog> logs = new ArrayList<>();

        // Group snapshots by day and pick the max reading for that day
        Map<LocalDate, EnvironmentalSnapshot> byDay = new java.util.LinkedHashMap<>();
        for (EnvironmentalSnapshot s : snapshots) {
            LocalDate day = s.getRecordedAt().atZone(ZoneOffset.UTC).toLocalDate();
            byDay.merge(day, s, (a, b) ->
                    (a.getPm25() != null && b.getPm25() != null && a.getPm25() >= b.getPm25()) ? a : b);
        }

        for (Map.Entry<LocalDate, EnvironmentalSnapshot> entry : byDay.entrySet()) {
            LocalDate day = entry.getKey();
            EnvironmentalSnapshot env = entry.getValue();
            int severity = computeSeverity(persona, env, rng);

            if (severity > 0) {
                SymptomLog sl = new SymptomLog();
                sl.setUserId(userId);
                sl.setLoggedAt(day.atTime(8, 0).toInstant(ZoneOffset.UTC));
                sl.setSeverity(severity);
                sl.setCityName(cityName);
                sl.setNotes(buildNote(persona, severity));
                sl.setDataOrigin("SEEDED_SYNTHETIC");
                logs.add(sl);
            }
        }

        if (!logs.isEmpty()) {
            symptomRepo.saveAll(logs);
        }

        log.info("Seeded {} symptom days for persona '{}'", logs.size(), persona);
        return logs.size();
    }

    /**
     * Computes a synthetic severity score (0-10) for a given persona and environmental reading.
     *
     * The three personas are deliberately driven by DIFFERENT factors at DIFFERENT
     * frequencies, so their learned fingerprints, symptom counts, confidence levels, and
     * trend shapes look clearly distinct rather than blurring together:
     *
     * - Alex (low sensitivity): only genuinely poor air bothers him, and only mildly.
     *   Single driver = PM2.5. Rare days, severity 1-3 (stays LOW confidence).
     * - Jordan (moderate): a classic pollen sufferer with a seasonal pattern. Single
     *   driver = grass/birch pollen. Regular days in season, severity 3-6.
     * - Morgan (high sensitivity): reacts to many things at low levels, often badly.
     *   Multi-driver = PM2.5 OR pollen OR humidity OR a pressure drop. Frequent, severe 6-10.
     *
     * Small random noise keeps consecutive days from being identical.
     *
     * @param persona the persona name
     * @param env     the environmental snapshot for this day
     * @param rng     seeded random for reproducibility across calls
     * @return severity 0-10 (0 = no symptoms)
     */
    int computeSeverity(String persona, EnvironmentalSnapshot env, Random rng) {
        double pm25     = env.getPm25() != null ? env.getPm25() : 0;
        double humidity = env.getHumidityPct() != null ? env.getHumidityPct() : 0;
        double grass    = env.getPollenGrass() != null ? env.getPollenGrass() : 0;
        double birch    = env.getPollenBirch() != null ? env.getPollenBirch() : 0;
        double pollen   = Math.max(grass, birch);
        double pressureDrop = env.getPressureDrop3h() != null ? env.getPressureDrop3h() : 0;

        return switch (persona) {
            case "alex" -> {
                // Pollution only, and only when it's genuinely poor. Rare and mild,
                // so he stays at LOW confidence (the "keep logging" story).
                if (pm25 > 26) yield 1 + rng.nextInt(3); // 1-3
                yield 0;
            }
            case "jordan" -> {
                // Pollen driven, seasonal. Regular moderate days when pollen is up.
                if (pollen > 12) yield 3 + rng.nextInt(4); // 3-6
                yield 0;
            }
            case "morgan" -> {
                // Sensitive across several factors, but NOT every single day, so the
                // engine still has good days to contrast against and learns clear,
                // low personal thresholds (which is what makes his risk read high).
                boolean triggered = pm25 > 11 || pollen > 8 || pressureDrop > 3;
                if (!triggered) yield 0;
                int base = 6 + rng.nextInt(4); // 6-9
                yield rng.nextInt(8) == 0 ? 10 : base; // occasional 10
            }
            default -> 0;
        };
    }

    private String buildNote(String persona, int severity) {
        return switch (persona) {
            case "alex"   -> severity >= 3 ? "Noticeable tightness on a hazy day" : "Mild scratchy throat";
            case "jordan" -> severity >= 6 ? "Rough pollen day, sneezing nonstop" : "Itchy eyes, runny nose";
            case "morgan" -> severity >= 8 ? "Severe episode, needed my rescue inhaler"
                                           : "Significant symptoms, hard to be outside";
            default -> "Symptoms noted";
        };
    }
}
