package com.ashoo.storage.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;

/**
 * A medication the user registered themselves.
 *
 * The app never populates or suggests these — the user types their own name and picks
 * a category. Reminders only ever echo this back; nothing here is generated by Ashoo.
 * Uses Spring Data JDBC (CrudRepository) because the table has a BIGSERIAL primary key.
 *
 * Removal is a soft delete ({@code isActive = false}) so that historical symptom-log
 * entries referencing this medication's id stay meaningful.
 */
@Table("medication")
public class Medication {

    @Id
    private Long id;
    private String userId;
    private String name;
    private String medType;
    private String notes;
    private Boolean isActive;
    private Instant createdAt;

    public Medication() {}

    public Long    getId()        { return id; }
    public String  getUserId()    { return userId; }
    public String  getName()      { return name; }
    public String  getMedType()   { return medType; }
    public String  getNotes()     { return notes; }
    public Boolean getIsActive()  { return isActive; }
    public Instant getCreatedAt() { return createdAt; }

    public void setId(Long v)         { this.id = v; }
    public void setUserId(String v)   { this.userId = v; }
    public void setName(String v)     { this.name = v; }
    public void setMedType(String v)  { this.medType = v; }
    public void setNotes(String v)    { this.notes = v; }
    public void setIsActive(Boolean v){ this.isActive = v; }
    public void setCreatedAt(Instant v){ this.createdAt = v; }
}
