-- Correlation results per factor, recomputed on demand and cached here.
-- Kept indefinitely — small rows, high value. The full history of how the
-- model's understanding of the user's triggers has evolved over time.
CREATE TABLE correlation_result (
    id                    BIGSERIAL    PRIMARY KEY,
    user_id               VARCHAR(64)  NOT NULL DEFAULT 'ashoo-user',
    computed_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    factor_name           VARCHAR(64)  NOT NULL,   -- e.g., "pm25", "pollen_grass"
    best_lag_hours        INTEGER,                  -- 0, 24, 48, or 72 — lag where correlation peaks
    spearman_r            DOUBLE PRECISION,         -- Spearman's rho: -1.0 to 1.0
    point_biserial_r      DOUBLE PRECISION,         -- Point-biserial r: -1.0 to 1.0
    personal_threshold    DOUBLE PRECISION,         -- Youden's J optimal cut-point in raw units
    threshold_percentile  DOUBLE PRECISION,         -- Same threshold expressed as 0-100 percentile
    weight                DOUBLE PRECISION,         -- Normalized importance weight (all weights sum to 1.0)
    confidence_level      VARCHAR(8),               -- LOW, MEDIUM, HIGH
    symptom_days_used     INTEGER,
    total_days_used       INTEGER,
    -- Days where the predicted score was high but the user felt fine.
    -- Surfaced in the UI to show the model's limitations honestly.
    mismatch_count        INTEGER DEFAULT 0
);

-- Audit log of every daily briefing generated by the Claude API.
-- Used for debugging, cost tracking, and ensuring the disclaimer was always present.
CREATE TABLE briefing_log (
    id              BIGSERIAL    PRIMARY KEY,
    user_id         VARCHAR(64)  NOT NULL DEFAULT 'ashoo-user',
    generated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    risk_score      DOUBLE PRECISION,
    risk_label      VARCHAR(16),
    briefing_text   TEXT         NOT NULL,   -- Full text returned by the Claude API
    tokens_used     INTEGER,                  -- For cost monitoring
    is_demo         BOOLEAN      NOT NULL DEFAULT FALSE
);
